/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.proyectonomina.sql.CConexion;

/**
 *
 * @author JAVIERCITO
 */
public class AutorizarAusencia extends javax.swing.JFrame {
    private CConexion conexion;
    
    
   private void cargarSolicitudes() {
    DefaultTableModel modelo = (DefaultTableModel) txtSolicitudes.getModel();
    modelo.setRowCount(0); // Limpiar el modelo actual

    String query = "SELECT e.id_empleado, e.nombre, e.apellido, p.motivo, "
                 + "p.fecha_solicitud, p.fecha_inicio, p.fecha_final, es.descripcion AS estado "
                 + "FROM Permisos p "
                 + "JOIN Empleado e ON p.id_empleado = e.id_empleado "
                 + "JOIN Estado es ON p.id_estado = es.id_estado "
                 + "WHERE es.descripcion = 'pendiente' "
                 + "ORDER BY p.fecha_solicitud ASC";

    try (Connection conn = new CConexion().establecerConexion(); 
         PreparedStatement stmt = conn.prepareStatement(query);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            Object[] fila = new Object[8]; // Ajusta el tamaño del array según el número de columnas
            fila[0] = rs.getInt("id_empleado"); // ID de empleado
            fila[1] = rs.getString("nombre"); // Nombre
            fila[2] = rs.getString("apellido"); // Apellido
            fila[3] = rs.getString("motivo"); // Motivo de ausencia
            fila[4] = rs.getDate("fecha_solicitud"); // Fecha de solicitud
            fila[5] = rs.getDate("fecha_inicio"); // Fecha de inicio
            fila[6] = rs.getDate("fecha_final"); // Fecha final
            fila[7] = rs.getString("estado"); // Estado
            modelo.addRow(fila);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar las solicitudes: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}




    public AutorizarAusencia() {
        initComponents();
        cargarSolicitudes();
        conexion = new CConexion();
        
        txtSolicitudes.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = txtSolicitudes.getSelectedRow();
            if (filaSeleccionada != -1) { // Asegurarse de que se ha seleccionado una fila
                txtCodigoEmpleado.setText(txtSolicitudes.getValueAt(filaSeleccionada, 0).toString());
                txtNombre.setText(txtSolicitudes.getValueAt(filaSeleccionada, 1).toString());
                txtApellido.setText(txtSolicitudes.getValueAt(filaSeleccionada, 2).toString());
                txtMotivo.setText(txtSolicitudes.getValueAt(filaSeleccionada, 3).toString());
                txtFechaInicio.setText(txtSolicitudes.getValueAt(filaSeleccionada, 5).toString());
                txtFechaFinal.setText(txtSolicitudes.getValueAt(filaSeleccionada, 6).toString());
            }
        }
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSolicitudes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigoEmpleado = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtApellido = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtFechaInicio = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtFechaFinal = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        rbtnDescSalario = new javax.swing.JRadioButton();
        rbtnDescVaca = new javax.swing.JRadioButton();
        rbtnSinDescuento = new javax.swing.JRadioButton();
        btnAutorizar = new javax.swing.JButton();
        btnDenegar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setText("Gestión de Solicitudes de Ausencia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 590, 50));

        txtSolicitudes.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Empleado", "Nombres", "Apellidos", "Motivo Ausencia", "Fecha Solicitud", "Fecha Inicio", "Fecha Final", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        txtSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(txtSolicitudes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 54, 750, 93));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Empleado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 195, 130, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 232, 86, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 263, 70, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de Inicio: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 298, 120, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel6.setText("Fecha final:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 332, 100, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel7.setText("Motivo: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 361, 100, -1));

        txtCodigoEmpleado.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtCodigoEmpleado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txtCodigoEmpleado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 118, -1));

        txtNombre.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtNombre.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(txtNombre);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 366, -1));

        txtApellido.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtApellido.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(txtApellido);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 366, -1));

        txtFechaInicio.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtFechaInicio.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(txtFechaInicio);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 366, -1));

        txtFechaFinal.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtFechaFinal.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(txtFechaFinal);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 366, -1));

        txtMotivo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtMotivo.setColumns(20);
        txtMotivo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtMotivo.setRows(5);
        jScrollPane7.setViewportView(txtMotivo);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 366, -1));

        rbtnDescSalario.setBackground(new java.awt.Color(255, 255, 255));
        rbtnDescSalario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        rbtnDescSalario.setText("Descuento Salario");
        jPanel1.add(rbtnDescSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        rbtnDescVaca.setBackground(new java.awt.Color(255, 255, 255));
        rbtnDescVaca.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        rbtnDescVaca.setText("Descuento Vacaciones");
        jPanel1.add(rbtnDescVaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        rbtnSinDescuento.setBackground(new java.awt.Color(255, 255, 255));
        rbtnSinDescuento.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        rbtnSinDescuento.setText("Sin Descuento");
        jPanel1.add(rbtnSinDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 130, -1));

        btnAutorizar.setBackground(new java.awt.Color(153, 153, 153));
        btnAutorizar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnAutorizar.setText("Autorizar");
        btnAutorizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAutorizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 130, -1));

        btnDenegar.setBackground(new java.awt.Color(153, 153, 153));
        btnDenegar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnDenegar.setText("Denegar");
        btnDenegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDenegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenegarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDenegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 120, -1));

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarActionPerformed
       
    }//GEN-LAST:event_btnAutorizarActionPerformed

    private void btnDenegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenegarActionPerformed
        
    }//GEN-LAST:event_btnDenegarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard ventanaprincipal = new Dashboard();
        ventanaprincipal.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutorizarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutorizarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutorizarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutorizarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutorizarAusencia().setVisible(true);
                System.out.print("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDenegar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JRadioButton rbtnDescSalario;
    private javax.swing.JRadioButton rbtnDescVaca;
    private javax.swing.JRadioButton rbtnSinDescuento;
    private javax.swing.JTextPane txtApellido;
    private javax.swing.JTextPane txtCodigoEmpleado;
    private javax.swing.JTextPane txtFechaFinal;
    private javax.swing.JTextPane txtFechaInicio;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextPane txtNombre;
    private javax.swing.JTable txtSolicitudes;
    // End of variables declaration//GEN-END:variables
}
