/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import com.mycompany.proyectonomina.EmpleadoCBD;
import com.mycompany.proyectonomina.sql.CConexion;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


public class ComisionProduccion extends javax.swing.JFrame {
    private int idEmpleado;

    public ComisionProduccion(int idEmpleado) {
        this.idEmpleado = idEmpleado;
        initComponents();
        txtCodigoEmpleado.setText(String.valueOf(idEmpleado));
        mostrarNombreEmpleado();
    }
    
    public ComisionProduccion() {
        initComponents();
    }
    private void mostrarNombreEmpleado() {
        // Llama al método del DAO para obtener el nombre completo
        String nombreCompleto = EmpleadoCBD.obtenerNombreCompleto(idEmpleado);
        txtNombre.setText(nombreCompleto); // Muestra el nombre en el JTextField
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPiezasLaboradas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCalcularComision = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComision = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        btnGuardarComision = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCodigoEmpleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setText("Comisiones de Producción");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 18, 446, 32));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel2.setText("Piezas Laboradas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 115, -1, -1));

        txtPiezasLaboradas.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtPiezasLaboradas.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jPanel1.add(txtPiezasLaboradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 74, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Thin", 1, 14)); // NOI18N
        jLabel3.setText("Bonificación por pieza (Q0.01)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 147, 220, 20));

        btnCalcularComision.setBackground(new java.awt.Color(153, 153, 153));
        btnCalcularComision.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnCalcularComision.setText("Calcular Comisión");
        btnCalcularComision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularComisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtComision.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtComision.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(txtComision);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 129, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setText("Comisión:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 229, 90, -1));

        btnGuardarComision.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardarComision.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnGuardarComision.setText("Guardar");
        btnGuardarComision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 263, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegresar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 263, 140, -1));

        txtNombre.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtNombre.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 250, -1));

        txtCodigoEmpleado.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtCodigoEmpleado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCodigoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 74, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCodigoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpleadoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        IngresarComisiones ventanaingresarcomisiones = new IngresarComisiones();
        ventanaingresarcomisiones.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCalcularComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularComisionActionPerformed
            calcularBonificacion(); 
    }                                                   

    private void calcularBonificacion() {
        try {
            // Obtener el total de piezas laboradas del campo de texto
            int piezasLaboradas = Integer.parseInt(txtPiezasLaboradas.getText().trim());

            // Calcular la bonificación (Q.0.01 por pieza)
            double bonificacion = piezasLaboradas * 0.01;

            // Mostrar el monto de la bonificación en el JTextPane
            txtComision.setText(String.format("%.2f", bonificacion)); // Formato con dos decimales
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en Piezas Laboradas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularComisionActionPerformed

    private void btnGuardarComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComisionActionPerformed
            guardarComision();
    }//GEN-LAST:event_btnGuardarComisionActionPerformed
    private void guardarComision() {
    Connection connection = null;
    PreparedStatement preparedStatement = null;

    try {
        CConexion cConexion = new CConexion();
        connection = cConexion.getConnection(); // Obtener la conexión

        if (connection == null) {
            JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir si la conexión es nula
        }

        // Obtener los datos necesarios
        int idEmpleado = this.idEmpleado; // ID del empleado
        int numeroPiezas = Integer.parseInt(txtPiezasLaboradas.getText().trim()); // Piezas laboradas
        double montoTotal = Double.parseDouble(txtComision.getText().trim()); // Monto total de la comisión

        // Consulta SQL para insertar la comisión
        String sql = "INSERT INTO Bonificacion_Productividad (id_empleado, numero_piezas, monto_total) VALUES (?, ?, ?)";
        preparedStatement = connection.prepareStatement(sql);
        preparedStatement.setInt(1, idEmpleado);
        preparedStatement.setInt(2, numeroPiezas);
        preparedStatement.setDouble(3, montoTotal);

        // Ejecutar la inserción
        int filasInsertadas = preparedStatement.executeUpdate();
        if (filasInsertadas > 0) {
            JOptionPane.showMessageDialog(this, "Comisión guardada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la comisión.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en las piezas o monto.", "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Cerrar recursos
        try {
            if (preparedStatement != null) preparedStatement.close();
            if (connection != null) connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComisionProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComisionProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComisionProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComisionProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComisionProduccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularComision;
    private javax.swing.JButton btnGuardarComision;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextPane txtComision;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPiezasLaboradas;
    // End of variables declaration//GEN-END:variables
}
