/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import com.mycompany.proyectonomina.EmpleadoCBD;
import com.mycompany.proyectonomina.sql.CConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class ComisionVentas extends javax.swing.JFrame {
    private int idEmpleado;
    

    public ComisionVentas(int idEmpleado) {
        this.idEmpleado = idEmpleado;
        initComponents();
        txtCodigoEmpleado.setText(String.valueOf(idEmpleado));
        mostrarNombreEmpleado();
    }
    public ComisionVentas() {
        initComponents();
    }
    private void mostrarNombreEmpleado() {
        
        String nombreCompleto = EmpleadoCBD.obtenerNombreCompleto(idEmpleado);
        txtNombre.setText(nombreCompleto); // Muestra el nombre en el JTextField
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPorcentaje = new javax.swing.JTextPane();
        btnCalcularComision = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComision = new javax.swing.JTextPane();
        btnGuardarComision = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCodigoEmpleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setText("Comisiones de Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 400, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 73, 256, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel3.setText("Total Venta Realizada:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 25));

        txtTotalVenta.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtTotalVenta.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jPanel1.add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 91, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setText("Porcentaje de comision:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtPorcentaje.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtPorcentaje.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(txtPorcentaje);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 53, -1));

        btnCalcularComision.setBackground(new java.awt.Color(153, 153, 153));
        btnCalcularComision.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnCalcularComision.setText("Calcular Comisión");
        btnCalcularComision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularComisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel5.setText("Comisión:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 71, -1));

        txtComision.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtComision.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(txtComision);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 114, -1));

        btnGuardarComision.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardarComision.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnGuardarComision.setText("Guardar Comisión");
        btnGuardarComision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 200, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegresar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 130, -1));

        txtNombre.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtNombre.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 272, -1));

        txtCodigoEmpleado.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtCodigoEmpleado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jPanel1.add(txtCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        IngresarComisiones ventanaingresarcomisiones = new IngresarComisiones();
        ventanaingresarcomisiones.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCalcularComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularComisionActionPerformed
        try {
        // Obtener el total de ventas del campo de texto y convertirlo a un número
        double totalVentas = Double.parseDouble(txtTotalVenta.getText().trim());
        double porcentaje = 0.0;
        double comision = 0.0;

        // Determinar el porcentaje según el rango de ventas
        if (totalVentas <= 100000) {
            porcentaje = 0.0; // 0%
        } else if (totalVentas <= 200000) {
            porcentaje = 2.5; // 2.5%
        } else if (totalVentas <= 400000) {
            porcentaje = 3.5; // 3.5%
        } else {
            porcentaje = 4.5; // 4.5%
        }

        // Calcular la comisión
        comision = (porcentaje / 100) * totalVentas;

        // Mostrar el porcentaje en el campo correspondiente
        txtPorcentaje.setText(String.valueOf(porcentaje) + "%");

        // Mostrar el monto de la comisión en el campo correspondiente
        txtComision.setText(String.format("%.2f", comision)); // Formato a 2 decimales

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en Total de Ventas.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnCalcularComisionActionPerformed

    private void btnGuardarComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComisionActionPerformed
        try {
        // Obtener datos desde la interfaz
        double montoVentas = Double.parseDouble(txtTotalVenta.getText().trim());
        double porcentajeComision = Double.parseDouble(txtPorcentaje.getText().trim().replace("%", "")); // Eliminar el símbolo de porcentaje
        double montoComision = Double.parseDouble(txtComision.getText().trim());

        // Asignar id_planilla, si lo tienes disponible, si no, puede ser null
        Integer idPlanilla = null; // Cambiar este valor según tu lógica

        // Crear la conexión
        CConexion conexion = new CConexion();
        Connection connection = conexion.getConnection();

        // Preparar la consulta SQL
        String sql = "INSERT INTO Comision_Ventas (id_empleado, id_planilla, monto_ventas, porcentaje_comision, monto_comision) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        
        // Establecer los valores
        preparedStatement.setInt(1, idEmpleado); // El id del empleado que recibiste
        if (idPlanilla != null) {
            preparedStatement.setInt(2, idPlanilla);
        } else {
            preparedStatement.setNull(2, java.sql.Types.INTEGER); // Para manejar el caso de que sea null
        }
        preparedStatement.setDouble(3, montoVentas);
        preparedStatement.setDouble(4, porcentajeComision);
        preparedStatement.setDouble(5, montoComision);

        // Ejecutar la inserción
        int rowsAffected = preparedStatement.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Comisión guardada exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la comisión.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese números válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar la comisión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnGuardarComisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComisionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComisionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComisionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComisionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComisionVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularComision;
    private javax.swing.JButton btnGuardarComision;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextPane txtComision;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextPane txtPorcentaje;
    private javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
