/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
    package Interfaz;

    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import com.mycompany.proyectonomina.sql.CConexion;
    import java.time.LocalDate;
    import java.time.format.DateTimeFormatter;
    import java.time.format.DateTimeParseException;

  
        public class SolicitudDeAusencia extends javax.swing.JFrame {

            private CConexion conexion; // Instancia de CConexion
            
            public SolicitudDeAusencia() {
                initComponents();
                conexion = new CConexion();
                
             
               

            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoEmpleado = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel5.setText("Motivo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 250, 80, -1));

        txtMotivo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtMotivo.setColumns(20);
        txtMotivo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtMotivo.setRows(5);
        jScrollPane2.setViewportView(txtMotivo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 273, 322, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel6.setText("SOLICITUD DE AUSENCIA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 8, 470, 30));

        txtCodigoEmpleado.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtCodigoEmpleado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCodigoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 74, -1));

        txtNombreEmpleado.setEditable(false);
        txtNombreEmpleado.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtNombreEmpleado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 310, 30));

        txtFechaInicio.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtFechaInicio.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 136, 90, -1));

        txtFechaFinal.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtFechaFinal.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinalActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 74, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de Inicio :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 29));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de Final :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 29));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Empleado: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel1.setText("Código de Empleado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, -1));

        btnEnviar.setBackground(new java.awt.Color(153, 153, 153));
        btnEnviar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 120, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegresar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Dashboard ventanaprincipal = new Dashboard();
        ventanaprincipal.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
         int idEmpleado = Integer.parseInt(txtCodigoEmpleado.getText());
    String fechaInicio = txtFechaInicio.getText();  // Fecha de inicio en formato DD-MM-YYYY
    String fechaFinal = txtFechaFinal.getText();     // Fecha final en formato DD-MM-YYYY
    String motivo = txtMotivo.getText();
    int idEstado = 1; // ID para estado "Pendiente"

    try (Connection conn = new CConexion().establecerConexion(); 
         PreparedStatement stmt = conn.prepareStatement("INSERT INTO Permisos (fecha_solicitud, fecha_inicio, fecha_final, id_empleado, motivo, id_estado) VALUES (?, ?, ?, ?, ?, ?)")) {

        // Fecha de solicitud actual
        java.sql.Date fechaSolicitud = java.sql.Date.valueOf(LocalDate.now());
        stmt.setDate(1, fechaSolicitud); 

        // Convertir fechaInicio de DD-MM-YYYY a YYYY-MM-DD
        LocalDate fechaInicioLocal;
        try {
            DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            fechaInicioLocal = LocalDate.parse(fechaInicio, inputFormatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha de inicio incorrecto. Por favor, usa DD-MM-YYYY.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        stmt.setDate(2, java.sql.Date.valueOf(fechaInicioLocal)); 

        // Convertir fechaFinal de DD-MM-YYYY a YYYY-MM-DD
        LocalDate fechaFinalLocal;
        try {
            DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            fechaFinalLocal = LocalDate.parse(fechaFinal, inputFormatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha final incorrecto. Por favor, usa DD-MM-YYYY.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        stmt.setDate(3, java.sql.Date.valueOf(fechaFinalLocal)); 

        stmt.setInt(4, idEmpleado); 
        stmt.setString(5, motivo); 
        stmt.setInt(6, idEstado); 

        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "Permiso enviado exitosamente.");
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al enviar el permiso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtCodigoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoActionPerformed
        try {
        int idEmpleado = Integer.parseInt(txtCodigoEmpleado.getText());
        String nombreCompleto = obtenerNombreEmpleado(idEmpleado);
        if (nombreCompleto != null) {
            txtNombreEmpleado.setText(nombreCompleto);
        } else {
            txtNombreEmpleado.setText("");
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtNombreEmpleado.setText("");
    }
    }//GEN-LAST:event_txtCodigoEmpleadoActionPerformed

    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed
        
    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void txtFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinalActionPerformed
    private String obtenerNombreEmpleado(int idEmpleado) {
        String nombre = null;
        Connection conn = null;

        try {
            conn = conexion.establecerConexion(); // Usando la instancia
            PreparedStatement stmt = conn.prepareStatement("SELECT nombre, apellido FROM Empleado WHERE id_empleado = ?");
            stmt.setInt(1, idEmpleado);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                nombre = rs.getString("nombre").trim() + " " + rs.getString("apellido").trim();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener datos del empleado.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Asegúrate de cerrar la conexión en el bloque finally
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error al cerrar la conexión.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        return nombre;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitudDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitudDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitudDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitudDeAusencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNombreEmpleado;
    // End of variables declaration//GEN-END:variables
}
